version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jvb-multigolang-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kgdhruj335ti"
s3_prefix = "jvb-multigolang-test"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""
image_repositories = []
